export const companyProfile = {
  ko: {
    hero: {
      eyebrow: 'Company',
      title: '워터비 연혁·기술자산',
      intro: '2021년 법인 설립 이후 주요 연혁과 수질계측기 형식승인, 등록특허, 기업·제품 인증을 정리했습니다.',
      metrics: [
        ['2021.10.05', '법인설립'],
        ['6건', '등록특허'],
        ['2건', '수질계측기 형식승인'],
      ],
    },
    identity: {
      eyebrow: 'Waterbee',
      title: '정확한 계측, 더 나은 물 관리',
      intro: '워터비는 현장 수질계측기와 제어·여과 시스템을 직접 개발하는 기술기업입니다. 측정 신뢰성, 유지관리성, 기존 설비와의 연결성을 함께 설계합니다.',
      missionLabel: 'Mission',
      mission: '신뢰할 수 있는 수질 데이터를 더 많은 현장에 제공합니다.',
      visionLabel: 'Vision',
      vision: '측정과 유지관리가 연결되는 실용적인 물 관리 표준을 만듭니다.',
    },
    history: {
      eyebrow: 'History',
      title: '법인 설립 이후 주요 연혁',
      intro: '지원사업을 나열하기보다 법인, 연구조직, 제품 승인과 기술자산의 주요 전환점을 기준으로 정리했습니다.',
      items: [
        ['2026', ['㈜에이치에스씨엠티와 글로벌 스마트 물관리 사업 상생협력 MOU 체결(01.23)', 'WATER KOREA 2026에서 한국상하수도협회·물에너지 기업들과 우즈베키스탄 거점 공동사업 다자간 MOU 체결(03.20)', 'K-water 성능개선 성과공유제 계약 체결(04.10)']],
        ['2024', ['하남 공장 등록(01.09)', '스마트 수질 측정 및 정밀 여과 시스템 K-water 공동특허 등록(04.15)', '잔류염소계 형식승인 취득(04.17)', 'HSCMT와 업무제휴협약 체결(06.16)', '벤처나라 지정, WBSC10 EMC 적합등록 및 탁도계·잔류염소계 시범구매제품 확인', '워터비·K-water 공동특허가 대한민국 발명특허대전 특허청장상 수상(11.27)']],
        ['2023', ['수질계측 핵심 특허 4건 등록(05~12월)', '탁도계 형식승인 취득(12.05)', '대한민국 물산업 혁신창업대전 사업화부문 장려상 수상(12.07)']],
        ['2022', ['청년창업사관학교 11기 졸업(02월)', 'WATERBEE 상표 등록(07.29)', 'K-water 제14기 협력 스타트업 협약 체결(10.31)']],
        ['2021', ['주식회사 워터비 설립(10.05)']],
      ],
    },
    patents: {
      eyebrow: 'Intellectual Property',
      title: '등록특허와 출원 현황',
      intro: '등록특허와 출원 중인 기술을 분리하고, 공동권리와 이전 취득 여부도 함께 표시합니다.',
      registeredLabel: '등록특허 6건',
      registered: [
        {
          number: '10-2658845',
          title: '스마트 수질 측정 및 정밀 여과 시스템',
          date: '2024.04.15',
          ownership: '워터비·한국수자원공사 공동권리',
        },
        {
          number: '10-2615508',
          title: '탁도 이상진단 시스템',
          date: '2023.12.14',
          ownership: '워터비 등록특허',
        },
        {
          number: '10-2607667',
          title: '탁도 측정 방법',
          date: '2023.11.24',
          ownership: '워터비 등록특허',
        },
        {
          number: '10-2570508',
          title: '비교측정 및 셀프교정 기능을 구비한 잔류염소 측정장치',
          date: '2023.08.21',
          ownership: '워터비 등록특허',
        },
        {
          number: '10-2532710',
          title: '탁도 및 잔류 염소 측정 시스템',
          date: '2023.05.10',
          ownership: '워터비 등록특허',
        },
        {
          number: '10-1132985',
          title: '릴레이 감시 시스템',
          date: '2023.11.24',
          ownership: '한국중부발전에서 무상 이전(2023.11.24)',
        },
      ],
      pendingLabel: '출원 중 1건',
      pending: [
        {
          number: '10-2024-0132853',
          title: '자가진단 다발형 정밀 수처리용 여과장치',
          date: '2024.09.30 출원',
          ownership: '심사 중',
        },
      ],
    },
    certifications: {
      eyebrow: 'Certifications',
      title: '인증 목록',
      intro: '제품 형식승인, 기업 확인과 공공조달 관련 인증을 정리했습니다.',
      items: [
        {
          category: '제품 형식승인',
          title: '탁도계 형식승인',
          number: '제DWMS-TM-2023-5호',
          detail: 'WBSC10 / WBTU10 · 국립환경과학원',
          date: '2023.12.05',
        },
        {
          category: '제품 형식승인',
          title: '잔류염소계 형식승인',
          number: '제DWMS-CM-2024-5호',
          detail: 'WBSC10 / WBFC10 · 국립환경과학원',
          date: '2024.04.17',
        },
        {
          category: '전자파 적합등록',
          title: 'WBSC10 EMC 적합등록',
          number: 'R-R-WBC-WBSC10',
          detail: '스마트 수질측정기기',
          date: '2024.09.30',
        },
        {
          category: '기업 확인',
          title: '벤처기업 확인',
          number: '제20241203030006호',
          detail: '혁신성장유형',
          date: '2024.09.29–2027.09.28',
        },
        {
          category: '기업 확인',
          title: '창업기업 확인',
          number: '제202601-27213-0075017호',
          detail: '창업기준 충족일 2021.10.05',
          date: '2026.01.12–2028.10.05',
        },
        {
          category: '연구조직',
          title: '연구개발전담부서 인정',
          number: '제2022152873호',
          detail: '연구개발전담부서',
          date: '최신 인정 2022.05.12',
        },
        {
          category: '공공조달',
          title: '벤처나라 지정',
          number: '제2024-05-0054호',
          detail: '조달청 벤처나라 지정상품',
          date: '2024.05.31–2027.05.30',
        },
        {
          category: '공공조달',
          title: '기술개발제품 시범구매',
          number: '제2024-00369호 / 제2024-00370호',
          detail: '탁도계 / 잔류염소계',
          date: '2024.10.16–2026.10.15',
        },
      ],
      note: '인증 범위와 대상 모델은 계약 또는 조달 전에 최신 증서를 확인해 주세요.',
    },
    links: {
      news: '최근 활동과 언론보도 보기',
      contact: '회사 및 제품 문의',
    },
  },
  en: {
    hero: {
      eyebrow: 'Company',
      title: 'Waterbee History & IP',
      intro: 'Company milestones, instrument type approvals, registered patents and certifications since incorporation in 2021.',
      metrics: [
        ['2021.10.05', 'Incorporated'],
        ['6', 'Registered patents'],
        ['2', 'Instrument type approvals'],
      ],
    },
    identity: {
      eyebrow: 'Waterbee',
      title: 'Dependable Measurement, Better Water',
      intro: 'Waterbee develops field water-quality instruments and control/filtration systems. Measurement confidence, maintainability and integration with existing facilities are designed together.',
      missionLabel: 'Mission',
      mission: 'Make dependable water-quality data available to more operating sites.',
      visionLabel: 'Vision',
      vision: 'Create a practical water-management standard that connects measurement and maintenance.',
    },
    history: {
      eyebrow: 'History',
      title: 'Milestones Since Incorporation',
      intro: 'The timeline focuses on turning points in the company, R&D organization, product approvals and technology assets rather than listing every support program.',
      items: [
        ['2026', ['Signed a smart-water-management cooperation MOU with HSCMT (Jan 23)', 'Signed a multilateral MOU with KWWA and water-energy companies at WATER KOREA 2026 for joint projects based in Uzbekistan (Mar 20)', 'Signed a K-water performance-improvement benefit-sharing agreement (Apr 10)']],
        ['2024', ['Registered the Hanam factory (Jan 9)', 'Registered a joint K-water patent for smart water-quality measurement and precision filtration (Apr 15)', 'Obtained residual chlorine analyzer type approval (Apr 17)', 'Signed a business cooperation agreement with HSCMT (Jun 16)', 'Received Venture Nara designation, WBSC10 EMC registration and pilot-purchase confirmation for turbidity and chlorine analyzers', "The Waterbee–K-water joint patent received the KIPO Commissioner's Award at the Korea Invention Patent Exhibition (Nov 27)"]],
        ['2023', ['Registered four core water-instrumentation patents (May–Dec)', 'Obtained turbidity meter type approval (Dec 5)', 'Received an Encouragement Award in the commercialization category at the Korea Water Industry Innovation Startup Competition (Dec 7)']],
        ['2022', ['Graduated from the 11th Youth Startup Academy (Feb)', 'Registered the WATERBEE trademark (Jul 29)', 'Signed the 14th K-water partner-startup agreement (Oct 31)']],
        ['2021', ['Waterbee Co., Ltd. incorporated (Oct 5)']],
      ],
    },
    patents: {
      eyebrow: 'Intellectual Property',
      title: 'Patents & Applications',
      intro: 'Registered patents are separated from the pending application, with joint ownership and transferred rights clearly identified.',
      registeredLabel: '6 registered patents',
      registered: [
        {
          number: '10-2658845',
          title: 'Smart Water-Quality Measurement and Precision Filtration System',
          date: '2024.04.15',
          ownership: 'Jointly owned by Waterbee and K-water',
        },
        {
          number: '10-2615508',
          title: 'Turbidity Abnormality Diagnosis System',
          date: '2023.12.14',
          ownership: 'Waterbee registered patent',
        },
        {
          number: '10-2607667',
          title: 'Turbidity Measurement Method',
          date: '2023.11.24',
          ownership: 'Waterbee registered patent',
        },
        {
          number: '10-2570508',
          title: 'Residual Chlorine Measurement Apparatus with Comparative Measurement and Self-Calibration',
          date: '2023.08.21',
          ownership: 'Waterbee registered patent',
        },
        {
          number: '10-2532710',
          title: 'Turbidity and Residual Chlorine Measurement System',
          date: '2023.05.10',
          ownership: 'Waterbee registered patent',
        },
        {
          number: '10-1132985',
          title: 'Relay Monitoring System',
          date: '2023.11.24',
          ownership: 'Transferred at no cost from KOMIPO (2023.11.24)',
        },
      ],
      pendingLabel: '1 pending application',
      pending: [
        {
          number: '10-2024-0132853',
          title: 'Self-Diagnostic Multi-Element Precision Water-Treatment Filter Apparatus',
          date: 'Filed 2024.09.30',
          ownership: 'Under examination',
        },
      ],
    },
    certifications: {
      eyebrow: 'Certifications',
      title: 'Certifications',
      intro: 'Instrument type approvals, corporate confirmations and public-procurement certifications.',
      items: [
        {
          category: 'Instrument type approval',
          title: 'Turbidity meter type approval',
          number: 'DWMS-TM-2023-5',
          detail: 'WBSC10 / WBTU10 · NIER',
          date: '2023.12.05',
        },
        {
          category: 'Instrument type approval',
          title: 'Residual chlorine analyzer type approval',
          number: 'DWMS-CM-2024-5',
          detail: 'WBSC10 / WBFC10 · NIER',
          date: '2024.04.17',
        },
        {
          category: 'EMC registration',
          title: 'WBSC10 EMC conformity registration',
          number: 'R-R-WBC-WBSC10',
          detail: 'Smart water-quality instrument',
          date: '2024.09.30',
        },
        {
          category: 'Corporate confirmation',
          title: 'Venture company confirmation',
          number: '20241203030006',
          detail: 'Innovation-growth category',
          date: '2024.09.29–2027.09.28',
        },
        {
          category: 'Corporate confirmation',
          title: 'Startup company confirmation',
          number: '202601-27213-0075017',
          detail: 'Startup criterion date: 2021.10.05',
          date: '2026.01.12–2028.10.05',
        },
        {
          category: 'R&D organization',
          title: 'Dedicated R&D department recognition',
          number: '2022152873',
          detail: 'Dedicated R&D department',
          date: 'Latest certificate 2022.05.12',
        },
        {
          category: 'Public procurement',
          title: 'Venture Nara designation',
          number: '2024-05-0054',
          detail: 'Public Procurement Service Venture Nara',
          date: '2024.05.31–2027.05.30',
        },
        {
          category: 'Public procurement',
          title: 'Pilot purchase of technology-developed products',
          number: '2024-00369 / 2024-00370',
          detail: 'Turbidity meter / residual chlorine analyzer',
          date: '2024.10.16–2026.10.15',
        },
      ],
      note: 'For contracting or procurement, confirm the latest certificate for scope and covered models.',
    },
    links: {
      news: 'View recent activity and press coverage',
      contact: 'Contact Waterbee',
    },
  },
} as const

export function getCompanyProfile(locale: string) {
  return companyProfile[locale === 'ko' ? 'ko' : 'en']
}
